### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by picolino0** [Firifire/OpenCvHololens#1]
I would love to give this a try in Unity, but I can't seem to figure out how to build this project. Could you perhaps release prebuilt binaries?

Thanks.

**Comment by picolino0** [comment]
I managed to get it to work. Here's a unitypackage with the dlls. I've also included a test script and the regular OpenCVSharp dlls so it works in the editor too. The test scene and script are incredibly slow on the HoloLens, but at least it works. I'm sure there's a way to get it to work properly.

The file was too big to upload to github, so here's a link:
https://drive.google.com/file/d/1O7ps-zocqcuLMA8R5fDgJEJyjjxNfLEK/view?usp=sharing

Edit: Link seemed to be broken, so I uploaded it to Google Drive instead.

**Comment by Firifire** [comment]
Hello,
Sorry for the late reply. Thank you for the uploading the unity package. 
I have uploaded the required dll in the release section.
For converting between Mat and texture. I suggest using the method in the attached script.

Texture2DToMat is about 4 times faster for me this way, but not much improvement for MatToTexture2D.

Also when deploying to the hololens, do try release build for additional performance boost.

[MatCnv.zip](https://github.com/Firifire/OpenCvSharp-UWP/files/1841252/MatCnv.zip)

**Comment by rafaP** [comment]
Thanks for the package for unity, but how do we use the face recognition in the unity?

**Comment by Firifire** [comment]
@rafaP  You should check with [OpenCvSharp](https://github.com/shimat/opencvsharp/) 
This just extends the functionality of the wrapper to work with UWP application

**Comment by rafaP** [comment]
I found a great example for face recognition.
But it was nice to have the latest version of openCV so we can have the Facemark.
And have a package as picolino0 as made.

**Comment by rafaP** [comment]
I used the MatCnv to convert the matrix to texture and texture to matrix, it work in unity but not in the hololens, it gives a memory error. How we can fix that?
