### ISSUE TITLE
Linker error building app after exporting IL2CPP in Unity 2018.2: GameAssembly.lib not found

### ISSUE THREAD

**Issue by gerwalk** [Firifire/OpenCvHololens#6]
My project in Unity 2018.2 is configured for IL2CPP. I have the DLLs imported in my Unity project and can successfully run the Webcam test provided by @picolino0 in #1 in the Editor using a USB Webcam.

When I open the exported solution in Visual Studio and attempt to build, it fails almost immediately saying that it can't locate **GameAssembly.lib**.

Visual Studio output:
`1>------ Build started: Project: xxx, Configuration: Release Win32 ------`
`1>pch.cpp`
`1>App.cpp`
`1>Main.cpp`
`1>UnityGenerated.cpp`
`1>d:\projects\xxx\uwp\xxx\app.cpp(26): warning C4973: 'Windows::UI::ViewManagement::IApplicationView2::SuppressSystemOverlays::set': marked as deprecated`
`1>d:\projects\xxx\uwp\xxx\app.cpp(26): note: Message: 'Use the TryEnterFullScreen method and IsFullScreenMode property instead of SuppressSystemOverlays. For more info, see MSDN.'`
`1>LINK : fatal error LNK1181: cannot open input file 'D:\Projects\xxx\UWP\build\bin\Win32\Release\GameAssembly.lib'`
`1>Done building project "xxx.vcxproj" -- FAILED.`
`========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

Indeed, the folder it's expecting to find GameAssembly.lib, which is generated at build time, in is totally empty, so it's as if it's not being copied over from another location or just not generated at all. There aren't any messages in the Unity console during export to indicate something went wrong.

**Comment by gerwalk** [comment]
Oof... it seems like this was my fault, or I just had some corrupted data sitting in my Library folder. I wiped Library and forced the project to do a full re-import.

When I initially imported the UnityPackage of DLLs from #1, I assumed all of the non-DLL files (such as the .pri, .winmd, etc. files) were not needed and I removed them to reduce clutter. Before I wiped my Library folder and did a reimport of the project, I also reimported all of those deleted files.

One of these two things appears to have resolved the error I was getting.

**Comment by firebrain7** [comment]
> Oof... it seems like this was my fault, or I just had some corrupted data sitting in my Library folder. I wiped Library and forced the project to do a full re-import.
> 
> When I initially imported the UnityPackage of DLLs from #1, I assumed all of the non-DLL files (such as the .pri, .winmd, etc. files) were not needed and I removed them to reduce clutter. Before I wiped my Library folder and did a reimport of the project, I also reimported all of those deleted files.
> 
> One of these two things appears to have resolved the error I was getting.
what does "wiped Library and forced the project to do a full re-import." this mean?
does it mean that delete all the library and re-import by yourself?

**Comment by firebrain7** [comment]
what does "wiped Library and forced the project to do a full re-import." this mean?
does it mean that delete all the library and re-import by yourself?

**Comment by firebrain7** [comment]
> Oof... it seems like this was my fault, or I just had some corrupted data sitting in my Library folder. I wiped Library and forced the project to do a full re-import.
> 
> When I initially imported the UnityPackage of DLLs from #1, I assumed all of the non-DLL files (such as the .pri, .winmd, etc. files) were not needed and I removed them to reduce clutter. Before I wiped my Library folder and did a reimport of the project, I also reimported all of those deleted files.
> 
> One of these two things appears to have resolved the error I was getting.

the build of my hololens application which use IL2CPP backend occurs the similar error which could not found GameAssembly.lib, and could not find the image.h for android(i have not use it). 
i have reimport the assets folder but not work, do you have any advice about it ?
thousand thanks

**Comment by Firifire** [comment]
This wrapper is meant for use with UWP application (not android)

Where did you get the DLLs? from the release section or from Issue #1 

Is this error occurring in Unity when exporting as Visual Studio project or in Visual Studio when building the project?

**Comment by firebrain7** [comment]
> This wrapper is meant for use with UWP application (not android)
> 
> Where did you get the DLLs? from the release section or from Issue #1
> 
> Is this error occurring in Unity when exporting as Visual Studio project or in Visual Studio when building the project?

Thank you Firifire. Actually, I did not use the dlls in this repository, and i jump to this link beacause i wonder how to solve the problem which could not find the gameAssembly.lib.
It is the error when building the project in VS 2017.
If you have any advice please tell me, thanks FiriFire.
