### ISSUE TITLE
Including inside an unity existing project.

### ISSUE THREAD

**Issue by valavakilian** [Firifire/OpenCvHololens#7]
Hi and thanks for sharing this. I am currently trying to use this library in an existing unity project that streams the camera from the Hololens and shows it to the user. I am trying to use OpenCvSharp-UWP to include the dnn module and do inference on that steam but I can't figure out how to add your wrapper to my project. I am a beginner with Hololens and unity and I would really appreciate any help .
Thank you

**Comment by Firifire** [comment]
For unity, download the Zip from the release section. Extract and Copy the DLLs to the "plugins" folder in your Unity project.
I cant guarantee the dnn module will work with this wrapper.
